http://localhost/api/users
Content-Type: application/json

{
  "fullName" : "Temirov Asadbek",
  "phoneNumber" : "+998972968668",
  "password" : "Asadbek8668",
  "home" : "24",
  "city" : "Tashkent",
  "street" : "Sergeli"

}